name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  check:
    name: Lint and check types
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v4
      - name: 'Set up Python'
        uses: actions/setup-python@v5
        with:
          python-version-file: '.python-version'
      - name: Lint
        run: make lint
      - name: Check formatting
        run: uv run ruff format src tests --check
      - name: Check types
        run: make check_types

  test:
    name: Test Python ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.10', '3.11', '3.12', '3.13']
        include:
          - os: macos-latest
            python-version: '3.13'
          - os: windows-latest
            python-version: '3.13'
    steps:
      - uses: actions/checkout@v4
      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up Python
        run: uv python install
      - name: Install the project
        run: uv python install
      - name: Run unit tests
        run: make test_unit
      - name: Run integration tests
        run: make test_integration
      - name: Run e2e tests
        run: make test_e2e
